import type { Metadata } from "next";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import Menu from "./components/Menu";
import UserDetails from "./components/UserDetails";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const cookieStore = cookies();
    if (!cookieStore.has("student")) redirect("/");

    return (
        <div className="py-14 px-20">
            <div className="grid grid-cols-4 gap-10 px-10 py-10 rounded-lg bg-white">
                <div className="col-span-1">
                    <Menu />
                </div>
                <div className="col-span-2">{children}</div>
                <div className="col-span-1">
                    <UserDetails />
                </div>
            </div>
        </div>
    );
}
